{% set name = "jsonschema2md" %}
{% set version = "1.7.0" %}
{% set sha256 = "d69a5b011bf355c005e3c18be4515ae46d2689b38b593ced8d03c5ab66ddbaf3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - jsonschema2md = jsonschema2md:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.5
    - babel =2.17.0
  run:
    - python >={{ python_min }},<4
    - PyYAML =6.0.3
    - markdown =3.9
    - babel =2.17.0

test:
  imports:
    - jsonschema2md
  commands:
    - pip check
    - jsonschema2md --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sbrunner/jsonschema2md
  summary: Convert JSON Schema to human-readable Markdown documentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ollyhensby
    - brynpickering
