{% set name = "jsonschema2md" %}
{% set version = "1.5.1" %}
{% set sha256 = "cdfc2d0e795945b624bb5713edad853aa2f45f6f8ad6392088d53019dd8c9fab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - jsonschema2md = jsonschema2md:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.5
  run:
    - python >={{ python_min }},<4
    - PyYAML =6.0.1

test:
  imports:
    - jsonschema2md
  commands:
    - pip check
    - jsonschema2md --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sbrunner/jsonschema2md
  summary: Convert JSON Schema to human-readable Markdown documentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ollyhensby
    - brynpickering
