{% set name = "jsonschema2md" %}
{% set version = "0.9.0" %}
{% set sha256 = "3ef34181679c48bbd1ac228ad1d6441051ceef58ba90cba6b931d0368e00ec77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - jsonschema2md = jsonschema2md:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=1.5
  run:
    - python >=3.7,<4
    - PyYAML =6.0.0

test:
  imports:
    - jsonschema2md
  commands:
    - pip check
    - jsonschema2md --help
  requires:
    - pip

about:
  home: https://github.com/sbrunner/jsonschema2md
  summary: Convert JSON Schema to human-readable Markdown documentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ollyhensby
    - brynpickering
