{% set name = "jsonschema2md" %}
{% set version = "1.0.0" %}
{% set sha256 = "01e18693c8dcdd643aa79ce757c5896877c590493422d23fd0bd76562fbc424b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - jsonschema2md = jsonschema2md:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.9
    - poetry >=1.5
  run:
    - python >=3.9,<4
    - PyYAML =6.0.1

test:
  imports:
    - jsonschema2md
  commands:
    - pip check
    - jsonschema2md --help
  requires:
    - pip

about:
  home: https://github.com/sbrunner/jsonschema2md
  summary: Convert JSON Schema to human-readable Markdown documentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ollyhensby
    - brynpickering
